---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
#  - _pvc
#  - ./arr-misc/ks.yaml
#  - ./bazarr/ks.yaml
#  - ./calibre/ks.yaml
#  - ./calibre-web/ks.yaml
#  - ./immich/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
#  - ./prowlarr/ks.yaml
#  - ./qbittorrent/ks.yaml
#  - ./radarr/ks.yaml
#  - ./readarr/ks.yaml
#  - ./readarr-audiobooks/ks.yaml
#  - ./sabnzbd/ks.yaml
#  - ./sonarr/ks.yaml
#  - ./tautulli/ks.yaml
  - ./tdarr/ks.yaml
