---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: blakeshome-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://blakeblackshear.github.io/blakeshome-charts/
  timeout: 3m
