---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./externalsecret.yaml
#  - gatus.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./volsync_backblazeb2.yaml
  - ./volsync_nas.yaml
