---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
#  - ./cloudflare-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
#  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./pihole-exporter/ks.yaml
  - ./promtail/ks.yaml
  - ./pve-exporter/ks.yaml
  - ./smartctl-exporter/ks.yaml
#  - ./snmp-exporter-nas/ks.yaml
#  - ./snmp-exporter-pdu/ks.yaml
  - ./snmp-exporter-s3400-48t6sp/ks.yaml
  - ./snmp-exporter-s3700-24t4f/ks.yaml
  - ./snmp-exporter-synology-nas/ks.yaml
  - ./snmp-exporter-t1500g-10mps/ks.yaml
#  - ./snmp-exporter-ups/ks.yaml
#  - ./snmp-generator/ks.yaml
  - ./speedtest-exporter/ks.yaml
#  - ./thanos/ks.yaml
  - ./unpoller/ks.yaml
