---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./volsync_nas.yaml
  - ./volsync_backblazeb2.yaml
  - ./config-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: node-red-configmap
    files:
      - ./resources/settings.js
generatorOptions:
  disableNameSuffixHash: true
#  annotations:
#    kustomize.toolkit.fluxcd.io/substitute: disabled
